### ISSUE TITLE
Issue with version 0.0.8 and Varnish 7.7.1

### ISSUE THREAD

**Issue by dbaio** [gquintard/vmod_fileserver#7]
Hi there, first, thanks for keeping this project updated.

I've noticed an issue in version 0.0.8 after updating to Varnish 7.7.1 today
```
Message from VCC-compiler:
VMOD fileserver: bad metadata
        (Syntax != 2.0)
        File name: /usr/local/lib/varnish/vmods/libvmod_fileserver.so
('/usr/local/etc/varnish/default.vcl' Line 11 Pos 8)
import fileserver;
-------##########-

Running VCC-compiler failed, exited with 2
VCL compilation failed
```

It was working with Varnish 7.7.0.

If anyone can help, it would be greatly appreciated. I apologize for being unable to assist with a patch here.

**Comment by gquintard** [comment]
Hi, thank you for reporting! I think that one was broken upstream, it might even not be a `varnish-rs` issue, I suspect Varnish actually broke the internal format. Give me a couple of days and I can confirm that

**Comment by gquintard** [comment]
@dbaio , sorry fot the delay, please try the latest version (`0.0.9`), it should fix it

**Comment by dbaio** [comment]
@gquintard I have tested with version `0.0.9` and `Varnish 7.7.1`... The error is gone.
Thank you so much.

**Comment by gquintard** [comment]
awesome, thank you for confirming!
